### PR TITLE
Techniques and sub-sections numbered 

### PR DESCRIPTION
**Pull request by MuhammedM294**
This commit only numbered the techniques list and the classification sub-section. If it's okay and approved, I will continue with other sub-sections.

### CODE REVIEW

**Comment by robmarkcole** [comment]
Fantastic, I think it is sufficient to number the techniques only, unless there is a good reason to number each resource as well?

**Comment by MuhammedM294** [comment]
Thanks! Actually numbering the sub-sections is the real motivation for doing this. So, one can know during exploring the repo which paper or code belongs to which technique without the need to go back to the heading. It's only one mouse scroll and you get lost in the repo :) 
Besides, it will save time for future edits/issues. You'll be able to localize the item to be edited easily.

**Comment by robmarkcole** [comment]
OK I understand now :)
Yes please complete the remaining sections for the PR, thanks!

**Comment by MuhammedM294** [comment]
This branch is ready to be merged now. It's a bit less aesthetically, but more practical, and organized,  and will definitely save much time for future issues.

**Comment by robmarkcole** [comment]
@MuhammedM294 there is an issue with Seg section - numbered 2.1, not 2

image

**Comment by MuhammedM294** [comment]
Yes, I did that intentionally because there are many sub-lists of segmentation resources such as segmentation - land use & land cover and segmentation - vegetation, crops & crop boundaries. So, treated Segmentation as a sub-section of the whole technique. There is another solution that also applies to objection detection and super-resolution techniques.

2. Segmentation 
    2.1 Segmentation (or any general name you specified)
          2.1.1. resources 
          2.1.2. resources 
    2.2. segmentation - land use & land cover
           2.2.1. re
           2.2.2. re
    2.3.segmentation - vegetation, crops & crop boundaries
          2.3.1. re
          2.3.2. re

The problem with Segmentation, object detection, and super-resolution techniques is that there are no names for the first sub-lists (2.1, 4.1, and 14.1 ). I think the solution mentioned above can work.

**Comment by robmarkcole** [comment]
Those first sections can be labelled `Segmentation - miscellaneous` etc

**Comment by MuhammedM294** [comment]
Yes, Agree. So, they should be renumbered with their resources to the last sub-section, right?

2. Segmentation
     2.1. Segmentation - Land use & land cover
     2.2. Segmentation - Vegetation, crops & crop boundaries
      .
      .
      .
      2.13. Segmentation - miscellaneous

**Comment by MuhammedM294** [comment]
@robmarkcole It's ready to be reviewed and merged now.

**Comment by robmarkcole** [comment]
Thanks @MuhammedM294 !

**Comment by MuhammedM294** [comment]
@robmarkcole My pleasure!

**Pull request merged**
